name: chip_manager_app
description: "ポーカーチップ管理アプリ"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # UI関連
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  flutter_spinkit: ^5.2.0
  
  # 状態管理
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  
  # バックエンド連携
  supabase_flutter: ^2.3.2
  
  # ルーティング
  go_router: ^13.2.0
  
  # ローカルストレージ
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  
  # QRコード関連
  mobile_scanner: ^3.5.7
  qr_flutter: ^4.1.0
  
  # チャート・グラフ
  fl_chart: ^0.66.2
  
  # ユーティリティ
  intl: ^0.19.0
  uuid: ^4.3.2
  logger: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
  
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Poppins-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700
